### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by colemar** [madcowfred/GoPostStuff#1]
Managed to build and install.
Had to do the following:
- avoid the Ubuntu golang package, install go1.2.linux-amd64.tar.gz from official Go site instead
- ignore [go get], it asks for github credentials and whatnot (I guess [git clone] is enough)
- copy simplenntp/ into src/github.com/madcowfred/gopoststuff/

Seems to work better than newsmangler. I miss the nzb generation though.

**Comment by budwig** [comment]
Awesome tool and faster upload speeds. Will you add the nzb creation like in newsmangler? Thanks.
