### ISSUE TITLE
Header Check?

### ISSUE THREAD

**Issue by shillshocked** [madcowfred/GoPostStuff#12]
It would be nice if you had a header check function like jbinup. I would use jbinup except it's not nearly as fast as yours for the initial post. The reposts are a cinch though because it has header checking. I'm sure you could do this with message-ids.

One reason I want this is that some news servers kick me off after an hour or two of posting...some weird connection issues (so I have to repost):

(ips removed)
WARNING   [pants:07] Post error: write tcp broken pipe
WARNING   [pants:07] Error while closing connection: write tcp broken pipe

**Comment by madcowfred** [comment]
This is basically #9, closing
