### ISSUE TITLE
Panic Error

### ISSUE THREAD

**Issue by ghost** [madcowfred/GoPostStuff#19]
I seem to be getting this error about 20% of the time. I only posted a small bit, but I can paste the entire error if needed.

Thanks

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x41029f]

goroutine 12 [running]:
runtime.panic(0x61b380, 0x8c7708)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.func·004(0xc21008b000, 0xc21008b0b0)
        /home/jonnyboy/go/src/github.com/f4n4t/gopoststuff/spawner.go:174 +0xa77
created by main.Spawner
        /home/jonnyboy/go/src/github.com/f4n4t/gopoststuff/spawner.go:190 +0x90b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc210000d78)
        /usr/lib/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc21004bf60)
        /usr/lib/go/src/pkg/sync/waitgroup.go:127 +0x14b
main.Spawner(0xc21000a050, 0x1, 0x1)
        /home/jonnyboy/go/src/github.com/f4n4t/gopoststuff/spawner.go:226 +0x9f7
main.main()
        /home/jonnyboy/go/src/github.com/f4n4t/gopoststuff/gopoststuff.go:156 +0xb84

**Comment by twiddern** [comment]
You may should post in the issue tracker of f4n4t, as you're using his sourcecode and not the one from madcowfred

**Comment by ghost** [comment]
Oops, you are correct.

**Comment by ghost** [comment]
No good. You can't post issues on his repo. Guess I'm SOL.
